### ISSUE TITLE
1.18 spawn

### ISSUE THREAD

**Issue by Kiryonn** [icedchai/icedchai-s-skeleton-mobs#2]
as you may know, in 1.18 the light level needed for spawn is 0. But i still get lots of skeletons knights that spawns in higher light levels.

**Comment by icedchai** [comment]
strange. i mixed skeleton knights in with the normal hostiles so this should work properly. ill review my mixins

**Comment by icedchai** [comment]
i tested this by sitting in a stone box filled with glow lichen. i didnt find any skeleton knights.
